name: Build and Test + Create Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag calculator:$(date +%s)
      
  push-on-dockerhub:
    
    runs-on: ubuntu-latest
    
    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: floo78340
          password: ${{ secrets.PASSWORD_REGISTRY }}
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: floo78340/calculator:v1.0.1
